"""
ai/bot_models.py
─────────────────────────────────────────────────────────────────────────────
Additional SQLAlchemy models for the AI trading bot.
These extend the existing models.py without modifying it.

Tables added:
  • bot_configs   — per-user bot configuration + AI parameters
  • signal_history — every generated signal (for backtesting + optimisation)
  • bot_runs      — log of each bot cycle
"""

from sqlalchemy import (
    Column, Integer, String, Float, Boolean, DateTime, JSON,
    ForeignKey, Text, Enum as SAEnum
)
from sqlalchemy.sql import func
import enum

from database import Base


class BotStatus(str, enum.Enum):
    stopped  = "stopped"
    running  = "running"
    paused   = "paused"
    error    = "error"


class SignalDirection(str, enum.Enum):
    long  = "long"
    short = "short"
    hold  = "hold"


class BotConfig(Base):
    """
    Per-user bot configuration.
    Stores exchange, symbols, risk params, and AI signal_scorer params.
    """
    __tablename__ = "bot_configs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, unique=True)

    # Status
    status = Column(SAEnum(BotStatus), default=BotStatus.stopped)

    # Exchange
    exchange = Column(String, default="binance")
    is_testnet = Column(Boolean, default=True)
    paper_mode = Column(Boolean, default=True)

    # Scanning config
    symbols = Column(JSON, default=list)       # ["BTCUSDT", "ETHUSDT", ...]
    timeframe = Column(String, default="1h")
    interval_seconds = Column(Integer, default=300)

    # Risk config (JSON blob)
    risk_config = Column(JSON, default=dict)

    # AI signal scorer parameters (JSON blob)
    # These are updated by self_optimizer.py
    signal_params = Column(JSON, default=dict)

    # Telegram notification settings
    telegram_enabled = Column(Boolean, default=False)
    notify_all_signals = Column(Boolean, default=False)    # notify even hold signals
    min_confidence_alert = Column(Float, default=75.0)

    # Stats cache (updated after each cycle)
    total_cycles = Column(Integer, default=0)
    total_signals = Column(Integer, default=0)
    total_trades = Column(Integer, default=0)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())


class SignalHistory(Base):
    """
    Every signal generated by the AI engine, win or lose.
    Used for backtesting analysis and self-optimisation.
    """
    __tablename__ = "signal_history"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    trade_id = Column(Integer, ForeignKey("trades.id"), nullable=True)   # null if not executed

    symbol = Column(String, nullable=False, index=True)
    timeframe = Column(String, default="1h")
    direction = Column(SAEnum(SignalDirection), nullable=False)
    confidence = Column(Float, default=0.0)

    entry_price = Column(Float)
    stop_loss = Column(Float)
    take_profit = Column(Float)
    risk_reward = Column(Float)

    # Score breakdown (JSON)
    score_breakdown = Column(JSON, default=dict)
    # Indicator snapshot (JSON)
    indicator_snapshot = Column(JSON, default=dict)
    # SMC summary (JSON)
    smc_data = Column(JSON, default=dict)
    # Sentiment at time of signal
    sentiment_score = Column(Float, default=0.0)
    sentiment_label = Column(String, default="neutral")

    # Whether the signal was acted on
    executed = Column(Boolean, default=False)
    execution_reason = Column(String, default="")   # "risk_approved" | "below_threshold" | "max_positions"

    # AI params used at time of signal (for reproducibility)
    params_snapshot = Column(JSON, default=dict)

    generated_at = Column(DateTime(timezone=True), server_default=func.now())


class BotRunLog(Base):
    """
    Log of each bot cycle execution. Useful for debugging and performance analysis.
    """
    __tablename__ = "bot_run_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    cycle_number = Column(Integer, default=0)
    signals_found = Column(Integer, default=0)
    trades_opened = Column(Integer, default=0)
    position_actions = Column(Integer, default=0)
    errors = Column(JSON, default=list)
    duration_ms = Column(Integer, default=0)
    summary = Column(JSON, default=dict)

    ran_at = Column(DateTime(timezone=True), server_default=func.now())
